### ISSUE TITLE
CarGoal Reset Service

### ISSUE THREAD

**Issue by retinfai** [UoA-CARES/autonomous_f1tenth#1]
# Desired Behavior
Implement a reset service for the car goal environment.
On reset:
- Set the position of the car back to 0, 0
- Set the position of the goal to be somewhere random

**Comment by retinfai** [comment]
class ResetServices(Node):

Calls the ResetServices class

    This makes the car move back to the original position which is [0,0,0]
       To make the car move back to original position, need to get current position of car into an array
       and get the car to move back from that position to [0,0,0]
    And this make the goal move to a random position on the grid
       To make the goal move to a random position, need to set max. x, y, z values of the grid and get the goal
       in a randomly generated postition

    Need clarification of where the current position is stored and if there is already an array for it 
    And where the maximum values of the x, y, z values of the grid are located

**Comment by pnor067** [comment]
class ResetServices(Node):

Calls the ResetServices class

This makes the car move back to the original position which is [0,0,0]
   To make the car move back to original position, need to get current position of car into an array
   and get the car to move back from that position to [0,0,0]
And this make the goal move to a random position on the grid
   To make the goal move to a random position, need to set max. x, y, z values of the grid and get the goal
   in a randomly generated postition

Need clarification of where the current position is stored and if there is already an array for it 
And where the maximum values of the x, y, z values of the grid are located

**Comment by retinfai** [comment]
To move the car, you do not need it's current position. Take a look at the SimulationServices set pose function.
In terms of generating the random goal, I agree to an extent. We can arbitrarily create a max/min bound – I usually use 10. 

One thing to consider here is not spawning the goal too close to the car

**Comment by retinfai** [comment]
Just went through the code, and looking good so far. I've moved your reset node into the environments package, anything related to the environments should be stored here.

**Comment by retinfai** [comment]
Just took a look at the Reset Service Implementation, and it's A LOT more complicated then I intended for you. I've gone ahead and implemented the CarWall reset node – use it as a guide for you work. Lmk if you have questions for something.
