### ISSUE TITLE
CarTrackEnvironment process killed

### ISSUE THREAD

**Issue by emilysteiner71** [UoA-CARES/autonomous_f1tenth#220]
When running sim, if it is not multi_track an error occurs: 

`[sim-9] Traceback (most recent call last):
[sim-9]   File "/home/emily/autonomous_f1tenth/install/controllers/lib/controllers/sim", line 33, in <module>
[sim-9]     sys.exit(load_entry_point('controllers', 'console_scripts', 'sim')())
[sim-9]   File "/home/emily/autonomous_f1tenth/build/controllers/controllers/sim.py", line 25, in main
[sim-9]     state, _ = env.reset()
[sim-9]   File "/home/emily/autonomous_f1tenth/build/environments/environments/CarTrackEnvironment.py", line 236, in reset
[sim-9]     self.track_model = self.all_track_models[self.current_track_key]
[sim-9] AttributeError: 'CarTrackEnvironment' object has no attribute 'current_track_key'`

I assume this is because the self.current_track_key variable is only instantiated when multi_track is true

**Comment by Doge-God** [comment]
https://github.com/UoA-CARES/autonomous_f1tenth/pull/221
